version: 2
jobs:
  build:
    working_directory: ~/build
    docker:
      - image: docker:git
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          exclusive: true
      - run:
          name: Build image
          command: |
            docker build -t circleci .
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker tag circleci:latest vlcty/circleci:$CIRCLE_BUILD_NUM
              docker push vlcty/circleci:$CIRCLE_BUILD_NUM
            else
              echo "Skipping deploy for non-master branch builds (#${CIRCLE_BUILD_NUM})"
            fi
